FROM php:8.3-fpm

RUN apt-get update && apt-get install -y \
    libzip-dev \
    libicu-dev \
    libxml2-dev \
    libxslt-dev \
    libpng-dev \
    libjpeg-dev \
    unzip \
    git \
    && docker-php-ext-install \
        bcmath \
        intl \
        soap \
        xsl \
        zip \
        gd \
        pdo_mysql \
        sockets \
        ftp \
    && rm -rf /var/lib/apt/lists/*
